# Generated by Django 6.0.1 on 2026-02-02 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=255)),
                ('Summary', models.TextField()),
                ('NewsLink', models.TextField(max_length=255)),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('Administrator', models.ForeignKey(db_column='ADMIN_ID', on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
                ('MediaFiles', models.ForeignKey(db_column='MEDIA_FILES_ID', on_delete=django.db.models.deletion.CASCADE, to='media.media')),
            ],
            options={
                'db_table': 'NEWS',
            },
        ),
    ]
