# Generated by Django 6.0.1 on 2026-02-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('news', '0002_remove_news_mediafiles_news_mediapath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='MediaPath',
            field=models.ForeignKey(blank=True, db_column='PATH', on_delete=django.db.models.deletion.CASCADE, to='media.media'),
        ),
    ]
