# Generated by Django 6.0.1 on 2026-02-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('news', '0003_alter_news_mediapath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='MediaPath',
        ),
        migrations.AddField(
            model_name='news',
            name='MediaFiles',
            field=models.ForeignKey(db_column='MEDIA_FILES_ID', default='', on_delete=django.db.models.deletion.CASCADE, to='media.media'),
            preserve_default=False,
        ),
    ]
