# Generated by Django 6.0.1 on 2026-02-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('news', '0004_remove_news_mediapath_news_mediafiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='MediaFiles',
            field=models.ForeignKey(db_column='MEDIA_FILES_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
    ]
