# Generated by Django 6.0.1 on 2026-03-02 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_mediafiles'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Administrator',
            field=models.ForeignKey(db_column='ADMIN_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.admin'),
        ),
    ]
