# Generated by Django 6.0.1 on 2026-03-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Summary', models.TextField()),
                ('MaterialsLink', models.TextField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('Administrator', models.ForeignKey(db_column='ADMIN_ID', on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
                ('MediaFiles', models.ForeignKey(db_column='MEDIA_FILES_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'db_table': 'MATERIALS',
            },
        ),
    ]
