# Generated by Django 6.0.1 on 2026-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
