# Generated by Django 5.2.11 on 2026-03-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_materials_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
