# Generated by Django 6.0.1 on 2026-04-30 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='MediaFiles',
        ),
        migrations.AddField(
            model_name='articles',
            name='Event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='Tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='Year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
