# Generated by Django 6.0.1 on 2026-04-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_articles_mediafiles_articles_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Tag',
            field=models.TextField(choices=[('Artigo Completo', 'Artigocompleto'), ('Resumo Expandido', 'Resumoexpandido'), ('Poster', 'Poster')], default='Artigo Completo'),
        ),
    ]
