# Generated by Django 6.0.1 on 2026-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Tag',
            field=models.TextField(choices=[('ARTIGO_COMPLETO', 'Artigo Completo'), ('RESUMO_EXPANDIDO', 'Resumo Expandido'), ('POSTER', 'Poster')], default='ARTIGO_COMPLETO'),
        ),
    ]
