# Generated by Django 6.0.1 on 2026-04-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articles_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Tag',
            field=models.CharField(choices=[('Artigo Completo', 'Artigo Completo'), ('Resumo Expandido', 'Resumo Expandido'), ('Poster', 'Poster')], default='Artigo Completo', max_length=20),
        ),
    ]
