# Generated by Django 6.0.1 on 2026-05-08 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articles_tag'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='MediaFiles',
            field=models.ForeignKey(db_column='MEDIA_FILES_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media'),
        ),
    ]
