# Generated by Django 6.0.1 on 2026-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_articles_mediafiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
