# Generated by Django 6.0.1 on 2026-05-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_articles_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='ArticleLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
