# Generated by Django 5.2.11 on 2026-03-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_alter_media_id'),
        ('users', '0004_alter_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('EducationLevel', models.TextField()),
                ('Role', models.IntegerField(choices=[('Coordenador', 'Coordenador'), ('Pesquisador', 'Pesquisador'), ('colaborador', 'Colaborador'), ('Egresso', 'Egresso')], default='Pesquisador')),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('Administrator', models.ForeignKey(db_column='ADMIN_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.admin')),
                ('MediaFiles', models.ForeignKey(db_column='MEDIA_FILES_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.media')),
            ],
            options={
                'db_table': 'TEAM_CARDS',
            },
        ),
    ]
