# Generated by Django 6.0.1 on 2026-03-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='LinkLattes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='Linked',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Role',
            field=models.TextField(choices=[('Coordenador', 'Coordenador'), ('Pesquisador', 'Pesquisador'), ('Colaborador', 'Colaborador'), ('Egresso', 'Egresso')], default='Pesquisador'),
        ),
    ]
