# Generated by Django 5.2.11 on 2026-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Role',
            field=models.TextField(choices=[('Coordenador', 'Coordenador'), ('Pesquisador', 'Pesquisador'), ('colaborador', 'Colaborador'), ('Egresso', 'Egresso')], default='Pesquisador'),
        ),
    ]
