# Generated by Django 6.0 on 2026-02-01 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=255, unique=True)),
                ('Path', models.CharField(max_length=500)),
                ('TypeFile', models.CharField(max_length=50)),
                ('SizeBytes', models.IntegerField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(db_column='ADMINISTRADOR_ID', on_delete=django.db.models.deletion.CASCADE, to='users.admin')),
            ],
            options={
                'db_table': 'MEDIA_FILES',
            },
        ),
    ]
