# Generated by Django 5.2.11 on 2026-03-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, unique=True)),
                ('VideoUrl', models.TextField()),
                ('CreateAt', models.DateTimeField(auto_now_add=True)),
                ('Administrator', models.ForeignKey(db_column='ADMIN_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.admin')),
            ],
            options={
                'db_table': 'VIDEO',
            },
        ),
    ]
